"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](#9A348E)\
$os\
[](bg:#DA627D fg:#9A348E)\
[](bg:#DA627D)\
[](fg:#DA627D bg:#FCA17D)\
$directory\
[](fg:#FCA17D bg:#86BBD8)\
[](bg:#86BBD8)\
[](fg:#86BBD8 bg:#06969A)\
$git_branch\
$git_status\
${custom.git_filler}\
[](fg:#06969A bg:#33658A)\
$docker_context\
[](fg:#33658A)\
"""

right_format = """$status$cmd_duration"""

[os]
disabled = false
style = "bold fg:#11111B bg:#9A348E"
format = '[ $symbol ]($style)'

[os.symbols]
Fedora = ""

[directory]
style = "fg:#11111B bg:#FCA17D"
format = "[  $path ]($style)"
home_symbol = "~"
truncation_length = 4
truncation_symbol = "⋯/"
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Projects" = "󰲋 "
"Coding" = "󰲋 "

[git_branch]
symbol = ""
style = "fg:#11111B bg:#06969A"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#11111B bg:#06969A"
format = '[$all_status$ahead_behind ]($style)'

conflicted = '=${count} '
ahead = '⇡${count} '
behind = '⇣${count} '
diverged = '⇕⇡${ahead_count}⇣${behind_count} '
untracked = '?${count} '
stashed = '\$${count} '
modified = '!${count} '
staged = '+${count} '
renamed = '»${count} '
deleted = '✘${count} '
typechanged = '~${count} '

[custom.git_filler]
when = '! git rev-parse --is-inside-work-tree >/dev/null 2>&1'
command = 'printf "ᓚᘏᗢ"'
style = "fg:#11111B bg:#06969A"
format = '[ $output ]($style)'
disabled = false

[docker_context]
symbol = " "
style = "fg:#11111B bg:#33658A"
format = '[ $symbol $context ]($style)'

[cmd_duration]
min_time = 100
format = '[$duration](bold yellow)'
show_milliseconds = true
disabled = false

[status]
disabled = false
format = '[$symbol$common_meaning$signal_name$maybe_int ]($style)'
symbol = '✘ '
success_symbol = '✔ '
success_style = 'bold green'
failure_style = 'bold red'
map_symbol = true
