# Previous / next media file
LEFT        playlist-prev
RIGHT       playlist-next

# Previous / next folder playlist
Shift+LEFT  playlist-prev-playlist
Shift+RIGHT playlist-next-playlist

# Seek within videos
Ctrl+LEFT   seek -5
Ctrl+RIGHT  seek 5
