# Previous / next media file
LEFT        playlist-prev
RIGHT       playlist-next

# Previous / next folder playlist
Ctrl+LEFT   playlist-prev-playlist
Ctrl+RIGHT  playlist-next-playlist

# Seek within videos
Shift+LEFT  seek -5
Shift+RIGHT seek 5
