# Dracula theme
[main]
font = monospace:size=12
prompt = "❯ "
terminal = kitty -e
fields = filename,name,generic,keywords,comment

[colors]
background = 282a36ff
text = f8f8f2ff
match = 8be9fdff
selection = 44475aff
selection-text = f8f8f2ff
selection-match = 50fa7bff
border = bd93f9ff

[border]
width = 2
radius = 8
