[mgr]
show_hidden = true

[opener]
nautilus = [
  { run = "nautilus -- %s", orphan = true, for = "linux", desc = "Open in Nautilus" },
]

[open]
prepend_rules = [
  { url = "*/", use = "nautilus" },
]

[[plugin.prepend_fetchers]]
id    = "git"
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
id    = "git"
url   = "*/"
run   = "git"
group = "git"
